## Krupa Modha
## 216270307101

In [1]:
'''to convert a list of numeric values into a one-dimensional NumPy array'''
import numpy as np
a2074 = [2,0,7,4]
print("Original List:",a2074)
b2074 = np.array(2074)
print("One-dimensional NumPy array: ",b2074)

Original List: [2, 0, 7, 4]
One-dimensional NumPy array:  2074


In [2]:
'''to create a 3x3 matrix with values ranging from 2 to 10'''
c2074 = np.arange(2, 11).reshape(3,3)
print(c2074)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [3]:
'''to append values at the end of an array'''
d2074 = [2,0]
print("Original array:")
print(d2074)
e2074 = np.append(d2074, [[7], [4]])
print("After append:")
print(e2074)

Original array:
[2, 0]
After append:
[2 0 7 4]


In [4]:
'''to create another shape from an array without changing its data (3*2 to 2*3)'''
f2074 = np.array([2, 0, 7, 0, 7,4 ])
g2074 = np.reshape(f2074,(3,2))
print("Reshape 3x2:")
print(g2074)
h2074 = np.reshape(f2074,(2,3))
print("Reshape 2x3:")
print(h2074)

Reshape 3x2:
[[2 0]
 [7 0]
 [7 4]]
Reshape 2x3:
[[2 0 7]
 [0 7 4]]
